---
airtrail_image: johly/airtrail:v3.2.2
airtrail_port: 3000
db_url: postgresql://airtrail:mysecretpassword@airtrail-db-service:5432/airtrail_db
db_name: airtrail_db
db_user: airtrail
db_password: mysecretpassword
